=== Lunariia/task_par/BanksXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/banks"
        xmlns:tns="http://www.example.com/banks" elementFormDefault="qualified">
    <element name="bank" type="tns:AbstractBank" abstract="true"/>
    <element name="state-bank" type="tns:StateBank" substitutionGroup="tns:bank"/>
    <element name="private-bank" type="tns:PrivateBank" substitutionGroup="tns:bank"/>
    <element name="central-bank" type="tns:CentralBank" substitutionGroup="tns:bank"/>
    <element name="banks">
        <complexType>
            <sequence>
                <element ref="tns:bank" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="deposit">
        <sequence>
            <element name="depositor" type="string"/>
            <element name="account-id" type="string"/>
            <element name="time-constraints" type="integer"/>
            <element name="persentage-type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="YEAR"/>
                        <enumeration value="MONTH"/>
                        <enumeration value="DAY"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
    <complexType name="AbstractBank">
        <sequence>
            <element name="deposit-type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="SAVING"/>
                        <enumeration value="DEMAND"/>
                        <enumeration value="METAL"/>
                        <enumeration value="URGENT"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="deposit" type="tns:deposit"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" default="N/A"/>
    </complexType>
    <complexType name="StateBank">
        <complexContent>
            <extension base="tns:AbstractBank">
                <sequence>
                    <element name="country" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="PrivateBank">
        <complexContent>
            <extension base="tns:AbstractBank">
                <sequence>
                    <element name="bank-owner" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="CentralBank">
        <complexContent>
            <extension base="tns:AbstractBank">
                <sequence>
                    <element name="rights" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== Lunariia/task_par/BanksXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks  BanksXSD.xsd">
    <!--First private bank-->
    <private-bank id="ID-1" name ="BelVeb">
        <deposit-type>SAVING</deposit-type>
        <deposit>
            <depositor>Mr.Poul</depositor>
            <account-id>42302</account-id>
            <time-constraints>365</time-constraints>
            <persentage-type>YEAR</persentage-type>
        </deposit>
        <bank-owner>VebCompany</bank-owner>
    </private-bank>
    <!--Second private bank-->
    <private-bank id="ID-2" name="TechnoBank">
        <deposit-type>DEMAND</deposit-type>
        <deposit>
            <depositor>Mr.Steve</depositor>
            <account-id>42303</account-id>
            <time-constraints>91</time-constraints>
            <persentage-type>MONTH</persentage-type>
        </deposit>
        <bank-owner>Techno</bank-owner>
    </private-bank>
    <!--First state bank-->
    <state-bank id="ID-3" name ="BelarusBank">
        <deposit-type>METAL</deposit-type>
        <deposit>
            <depositor>Person</depositor>
            <account-id>42304</account-id>
            <time-constraints>14</time-constraints>
            <persentage-type>DAY</persentage-type>
        </deposit>
        <country>Belarus</country>
    </state-bank>
    <!--Second state bank-->
    <state-bank id="ID-4" name ="WelfareBank">
        <deposit-type>URGENT</deposit-type>
        <deposit>
            <depositor>Mr.Mark</depositor>
            <account-id>42303</account-id>
            <time-constraints>92</time-constraints>
            <persentage-type>MONTH</persentage-type>
        </deposit>
        <country>Belarus</country>
    </state-bank>
    <!--First Central bank-->
    <central-bank id="ID-5" name ="CentralBank">
        <deposit-type>SAVING</deposit-type>
        <deposit>
            <depositor>Person</depositor>
            <account-id>42304</account-id>
            <time-constraints>14</time-constraints>
            <persentage-type>DAY</persentage-type>
        </deposit>
        <rights>Money</rights>
    </central-bank>
    <!--Second Central bank-->
    <central-bank id="ID-6" name ="CentralTmpBank">
        <deposit-type>URGENT</deposit-type>
        <deposit>
            <depositor>Mr.Mark</depositor>
            <account-id>42303</account-id>
            <time-constraints>92</time-constraints>
            <persentage-type>MONTH</persentage-type>
        </deposit>
        <rights>Money</rights>
    </central-bank>
</banks>
